<a href="https://colab.research.google.com/github/zlopezr/zlopezr/blob/main/8_Concat_append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade pandas

     |████████████████████████████████| 9.9MB 5.3MB/s 
ERROR: google-colab 1.0.0 has requirement pandas~=1.1.0; python_version >= "3.0", but you'll have pandas 1.2.3 which is incompatible.
  Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5


In [ ]:
import pandas as pd
import numpy as np
pd.__version__

'1.2.3'

In [ ]:
#Mostrar dos números decimales en un valor decimal
pd.options.display.float_format='{:.2f}'.format

In [ ]:
#Mostrar dos números decimales en un valor decimal con numpy
np.set_printoptions(precision=2)

In [ ]:
#Números aleatorios 
x1= np.random.rand(2,5)*10
x1

array([[2.29e-01, 4.33e+00, 5.91e-03, 6.37e+00, 2.37e+00],
       [3.67e+00, 5.90e+00, 6.71e+00, 6.80e+00, 6.43e+00]])

In [ ]:
#Números aleatorios negativos
x2= np.random.rand(2,5)*-1
x2

array([[-0.26, -0.19, -0.96, -0.89, -0.85],
       [-0.21, -0.08, -0.37, -0.82, -0.3 ]])

In [ ]:
np.concatenate([x1,x2])

array([[ 2.29e-01,  4.33e+00,  5.91e-03,  6.37e+00,  2.37e+00],
       [ 3.67e+00,  5.90e+00,  6.71e+00,  6.80e+00,  6.43e+00],
       [-2.59e-01, -1.88e-01, -9.55e-01, -8.92e-01, -8.50e-01],
       [-2.07e-01, -8.34e-02, -3.72e-01, -8.15e-01, -3.02e-01]])

In [ ]:
np.concatenate([x1,x2]).shape


(4, 5)

In [ ]:
np.concatenate([x1,x2],axis=1)

array([[ 2.29e-01,  4.33e+00,  5.91e-03,  6.37e+00,  2.37e+00, -2.59e-01,
        -1.88e-01, -9.55e-01, -8.92e-01, -8.50e-01],
       [ 3.67e+00,  5.90e+00,  6.71e+00,  6.80e+00,  6.43e+00, -2.07e-01,
        -8.34e-02, -3.72e-01, -8.15e-01, -3.02e-01]])

In [ ]:
np.concatenate([x1,x2],axis=1).shape

(2, 10)

In [ ]:
s1= pd.Series(x1[0],index=['a','b','c','d','e'])
s1

a   0.23
b   4.33
c   0.01
d   6.37
e   2.37
dtype: float64

In [ ]:
s2= pd.Series(x2[0],index=['c','d','e','f','g'])
s2

c   -0.26
d   -0.19
e   -0.96
f   -0.89
g   -0.85
dtype: float64

In [ ]:
pd.concat([s1,s2],axis=1)

0     1
a 0.23   NaN
b 4.33   NaN
c 0.01 -0.26
d 6.37 -0.19
e 2.37 -0.96
f  NaN -0.89
g  NaN -0.85

In [ ]:
s1.reset_index(drop=True)

0   0.23
1   4.33
2   0.01
3   6.37
4   2.37
dtype: float64

In [ ]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)],axis=1)

0     1
0 0.23 -0.26
1 4.33 -0.19
2 0.01 -0.96
3 6.37 -0.89
4 2.37 -0.85

In [ ]:
df1= pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 2.98 9.44
1 5.23 9.35
2 7.69 5.27

In [ ]:
df2= pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'],index=[2,3,4])
df2


a     b
2 -0.09 -0.83
3 -0.03 -0.96
4 -0.61 -0.51

In [ ]:
pd.concat([df1,df2],axis=1)

a    b     a     b
0 2.98 9.44   NaN   NaN
1 5.23 9.35   NaN   NaN
2 7.69 5.27 -0.09 -0.83
3  NaN  NaN -0.03 -0.96
4  NaN  NaN -0.61 -0.51

In [ ]:
pd.concat([df1,df2],axis=1,join='inner')

a    b     a     b
2 7.69 5.27 -0.09 -0.83