<a href="https://colab.research.google.com/github/zlopezr/zlopezr/blob/main/PrimerosPaso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!git clone https://github.com/zlopezr/zlopezr.git

fatal: destination path 'zlopezr' already exists and is not an empty directory.


In [ ]:
10+3

13

In [ ]:
2*3

6

In [ ]:
2**3

8

In [ ]:
D=0
D

0

In [ ]:
y=15


In [ ]:
D+y

15

In [ ]:
H='Hola'
y='Zaida'
H+' '+y


'Hola Zaida'

In [ ]:
[1,2,3,4,5,6]

[1, 2, 3, 4, 5, 6]

In [ ]:
Lista= [1,2,3,4,5,6]

In [ ]:
Lista[0]

1

In [ ]:
Lista[4]

In [ ]:
Lista[5]


6

In [ ]:
Lista[-1]

6

In [ ]:
Lista[1]

2

In [ ]:
Lista[+1]

2

In [ ]:
import numpy as np


In [ ]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.array([1,2,3,4,5,6]) + 10


array([11, 12, 13, 14, 15, 16])

In [ ]:
np.array([1,2,3,4,5,6])+5

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
np.array([1,2,3,4,5,6]).shape

(6,)

In [ ]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])
np.array([[1,2,3,4,5],[6,7,8,9,10]]).shape

(2, 5)

In [ ]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])[0][2]

3

In [ ]:
import pandas as pd


In [ ]:
#Series
pd.Series([10,9,8,7,6,5])

0    10
1     9
2     8
3     7
4     6
5     5
dtype: int64

In [ ]:
sr= pd.Series([10,9,8,7,6,5])

In [ ]:
sr.value_counts


<bound method IndexOpsMixin.value_counts of 0    10
1     9
2     8
3     7
4     6
5     5
dtype: int64>

In [ ]:
#Valores
sr.values

array([10,  9,  8,  7,  6,  5])

In [ ]:
#Cantidad total 
sr.shape


(6,)

In [ ]:
sr.values

array([10,  9,  8,  7,  6,  5])

In [ ]:
sr.index


RangeIndex(start=0, stop=6, step=1)

In [ ]:
sr[3]


7

In [ ]:
sr[[0,4,3]]

0    10
4     6
3     7
dtype: int64

In [ ]:
rs= pd.Series([10,9,8,7,6,5], index=['a','b','c','d','e','f'])

In [ ]:
rs

a    10
b     9
c     8
d     7
e     6
f     5
dtype: int64

In [ ]:
rs['a':'c']

a    10
b     9
c     8
dtype: int64

In [ ]:
rs[['a','d']]

a    10
d     7
dtype: int64

In [ ]:
#Dicionario
Dict_data= {'CO':100,'MX':200,'AR':300}
Dict_data

{'AR': 300, 'CO': 100, 'MX': 200}

In [ ]:
Dict_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [ ]:
Dict_data['MX']

200

In [ ]:
pd.Series(Dict_data, index=['CO','MX','PE'])

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [ ]:
import numpy as np
np.nan
np.nan+10


nan

In [ ]:
sr = pd.Series(Dict_data, index=['CO','MX','PE','AR'])
sr

CO    100.0
MX    200.0
PE      NaN
AR    300.0
dtype: float64

In [ ]:
sr.is_unique

True

In [ ]:
#Variables Nulas
sr.isnull()


CO    False
MX    False
PE     True
AR    False
dtype: bool

In [ ]:
sr.isnull([])